language: node_js
node_js:
  - "8.6.0"
  - "node"
env:
  - WEBPACK_VERSION= # Current, from package.json
  - WEBPACK_VERSION=4
install:
  - if [[ `npm -v` != 5.7* ]]; then npm install -g npm@'>=5.7.1'; fi
  - npm install
before_script:
  - if [[ -n "$WEBPACK_VERSION" ]]; then npm install --no-save webpack@$WEBPACK_VERSION; fi
branches:
  except:
    - gh-pages
stages:
  - test
  - build
jobs:
  include:
    - stage: test
      script:
        # Run tests
        - npm run test
    - stage: build
      script:
        - npm run build
